name: SurrealDB Driver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Git Checkout
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Eclipse Temurin is a popular JDK distribution

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Start SurrealDB
      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@v2
        with:
          surrealdb_version: latest
          surrealdb_port: 8000
          surrealdb_username: root
          surrealdb_password: root
          surrealdb_auth: false
          surrealdb_strict: false
          surrealdb_log: info
          surrealdb_additional_args: --allow-all
          surrealdb_retry_count: 30

      # Ensure Gradle is executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Run tests with Gradle
      - name: Run Tests
        run: ./gradlew test --info

      # Upload test results as an artifact (optional)
      - name: Upload Test Results
        if: always() # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/**/*.xml